// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Page = require("../../../core/components/page/Page.bs.js")
var React = require("react")
var LoginForm = require("../LoginForm.bs.js")

function LoginPage(Props) {
  return React.createElement(Page.make, {
    title: "Login",
    children: React.createElement(LoginForm.make, {}),
  })
}

var make = LoginPage

exports.make = make
/* Page Not a pure module */
