// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as SignupForm from "../components/SignupForm.bs.js"
import * as React$1 from "@ionic/react"

function SignupPage(Props) {
  return React.createElement(
    React$1.IonPage,
    {
      children: null,
    },
    React.createElement(React$1.IonHeader, {
      children: React.createElement(React$1.IonToolbar, {
        children: React.createElement(React$1.IonTitle, {
          children: "Create account",
        }),
      }),
    }),
    React.createElement(React$1.IonContent, {
      children: React.createElement(SignupForm.make, {}),
    })
  )
}

var make = SignupPage

export { make }
/* react Not a pure module */
