// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as SignupForm from "../form/SignupForm.bs.js"
import * as React$1 from "@ionic/react"

function SignupPage(Props) {
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement(React$1.IonHeader, {
      children: React.createElement(React$1.IonToolbar, {
        children: React.createElement(React$1.IonTitle, {
          children: "Create account",
        }),
      }),
    }),
    React.createElement(React$1.IonContent, {
      children: React.createElement(React$1.IonGrid, {
        children: React.createElement(React$1.IonRow, {
          children: React.createElement(React$1.IonCol, {
            children: React.createElement(SignupForm.make, {}),
            sizeMd: "5",
            sizeLg: "4",
          }),
          className: "ion-justify-content-center",
        }),
      }),
      className: "ion-padding",
    })
  )
}

var make = SignupPage

export { make }
/* react Not a pure module */
