// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Test = require("rescript-test/src/Test.bs.js")
var Assert = require("../assert/Assert.bs.js")
var Js_dict = require("rescript/lib/js/js_dict.js")
var FormState = require("../../app/core/rescript/form/FormState.bs.js")
var Belt_MapString = require("rescript/lib/js/belt_MapString.js")

Test.test("Gets values from state", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var result = FormState.mapFieldsToDict(state)
  var expected = Js_dict.fromArray([
    ["email", "myemail@gmail.com"],
    ["password", "12345678"],
  ])
  return Assert.assertDeepEqual(result, expected)
})

/*  Not a pure module */
