// Generated by ReScript, PLEASE EDIT WITH CARE

var IonContent = {}

var IonApp = {}

var Content = {
  IonContent: IonContent,
  IonApp: IonApp,
}

var IonHeader = {}

var IonToolbar = {}

var IonTitle = {}

var Toolbar = {
  IonHeader: IonHeader,
  IonToolbar: IonToolbar,
  IonTitle: IonTitle,
}

var IonPage = {}

var Navigation = {
  IonPage: IonPage,
}

var IonItem = {}

var IonLabel = {}

var Item = {
  IonItem: IonItem,
  IonLabel: IonLabel,
}

var IonInput = {}

var Input = {
  IonInput: IonInput,
}

export { Content, Toolbar, Navigation, Item, Input }
/* No side effect */
