// Generated by ReScript, PLEASE EDIT WITH CARE

var IonContent = {}

var IonHeader = {}

var IonToolbar = {}

var IonPage = {}

var IonApp = {}

var IonTitle = {}

export { IonContent, IonHeader, IonToolbar, IonPage, IonApp, IonTitle }
/* No side effect */
