// Generated by ReScript, PLEASE EDIT WITH CARE

var IonContent = {}

var IonApp = {}

var Content = {
  IonContent: IonContent,
  IonApp: IonApp,
}

var IonHeader = {}

var IonToolbar = {}

var IonTitle = {}

var Toolbar = {
  IonHeader: IonHeader,
  IonToolbar: IonToolbar,
  IonTitle: IonTitle,
}

var IonPage = {}

var Navigation = {
  IonPage: IonPage,
}

var IonItem = {}

var IonLabel = {}

var Item = {
  IonItem: IonItem,
  IonLabel: IonLabel,
}

var IonInput = {}

var Input = {
  IonInput: IonInput,
}

var IonCol = {}

var IonRow = {}

var Grid = {
  IonCol: IonCol,
  IonRow: IonRow,
}

var IonButton = {}

var Button = {
  IonButton: IonButton,
}

export { Content, Toolbar, Navigation, Item, Input, Grid, Button }
/* No side effect */
