// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.mjs"
import * as Caml_obj from "rescript/lib/es6/caml_obj.js"
import * as Belt_Array from "rescript/lib/es6/belt_Array.js"
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js"

function assertArrayEqual(result, expected) {
  return Test.assertion(
    undefined,
    undefined,
    function (res, exp) {
      return Belt_Array.eq(res, exp, Caml_obj.caml_equal)
    },
    result,
    expected
  )
}

function assertMapEqual(result, expected) {
  return Test.assertion(
    undefined,
    undefined,
    function (res, exp) {
      return Belt_MapString.eq(res, exp, Caml_obj.caml_equal)
    },
    result,
    expected
  )
}

export { assertArrayEqual, assertMapEqual }
/* Test Not a pure module */
