// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Test = require("rescript-test/src/Test.bs.js")
var Assert = require("./Assert.bs.js")
var Belt_MapString = require("rescript/lib/js/belt_MapString.js")
var SignupValidation = require("../app/auth/signup/form/SignupValidation.bs.js")

Test.test("Validates valid state", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var result = SignupValidation.validate(state)
  var expected = []
  return Assert.assertArrayEqual(result, expected)
})

Test.test("Invalidates invalid state", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "",
        error: "",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var result = SignupValidation.validate(state)
  var expected = [
    {
      name: "password",
      error: "This field is required",
    },
  ]
  return Assert.assertArrayEqual(result, expected)
})

/*  Not a pure module */
