// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.mjs"
import * as Assert from "./Assert.mjs"
import * as SignupReducer from "../app/auth/signup/form/SignupReducer.mjs"
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js"

Test.test("Handles Change action", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "",
        error: "Required",
      },
    ],
    [
      "password",
      {
        value: "",
        error: "Required",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var result = SignupReducer.reducer(state, {
    TAG: /* Change */ 0,
    name: "email",
    value: "myemail@gmail.com",
  })
  var expectedArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "",
        error: "Required",
      },
    ],
  ]
  var expected = Belt_MapString.fromArray(expectedArray)
  return Assert.assertMapEqual(result, expected)
})

Test.test("Handles SetErrors action", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var action = {
    TAG: /* SetErrors */ 1,
    _0: [
      {
        name: "email",
        error: "Required",
      },
    ],
  }
  var result = SignupReducer.reducer(state, action)
  var expectedArray = [
    [
      "email",
      {
        value: "",
        error: "Required",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var expected = Belt_MapString.fromArray(expectedArray)
  return Assert.assertMapEqual(result, expected)
})

export {}
/*  Not a pure module */
