// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Test = require("rescript-test/src/Test.bs.js")
var Assert = require("./Assert.bs.js")
var SignupReducer = require("../app/auth/signup/form/reducer/SignupReducer.bs.js")
var Belt_MapString = require("rescript/lib/js/belt_MapString.js")

Test.test("Handles Change action", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "",
        error: "Required",
      },
    ],
    [
      "password",
      {
        value: "",
        error: "Required",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var result = SignupReducer.reducer(state, {
    TAG: /* Change */ 0,
    name: "email",
    value: "myemail@gmail.com",
  })
  var expectedArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "",
        error: "Required",
      },
    ],
  ]
  var expected = Belt_MapString.fromArray(expectedArray)
  return Assert.assertMapEqual(result, expected)
})

Test.test("Handles SetErrors action", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var action = {
    TAG: /* SetErrors */ 1,
    _0: [
      {
        name: "email",
        error: "Required",
      },
    ],
  }
  var result = SignupReducer.reducer(state, action)
  var expectedArray = [
    [
      "email",
      {
        value: "",
        error: "Required",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var expected = Belt_MapString.fromArray(expectedArray)
  return Assert.assertMapEqual(result, expected)
})

/*  Not a pure module */
