// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Test = require("rescript-test/src/Test.bs.js")
var Assert = require("./Assert.bs.js")
var SignupOutput = require("../app/auth/signup/form/SignupOutput.bs.js")
var Belt_MapString = require("rescript/lib/js/belt_MapString.js")

Test.test("Gets values from state", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var result = SignupOutput.getOutput(state)
  var expectedArray = [
    ["email", "myemail@gmail.com"],
    ["password", "12345678"],
  ]
  var expected = Belt_MapString.fromArray(expectedArray)
  return Assert.assertMapEqual(result, expected)
})

/*  Not a pure module */
