// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.mjs"
import * as Assert from "./Assert.mjs"
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js"
import * as SignupValidation from "../app/auth/signup/form/SignupValidation.mjs"

Test.test("Validates valid state", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var result = SignupValidation.validate(state)
  var expected = []
  return Assert.assertArrayEqual(result, expected)
})

Test.test("Invalidates invalid state", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "",
        error: "",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var result = SignupValidation.validate(state)
  var expected = [
    {
      name: "password",
      error: "This field is required",
    },
  ]
  return Assert.assertArrayEqual(result, expected)
})

export {}
/*  Not a pure module */
