// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var FormState = require("../../../../core/form/state/FormState.bs.js")
var Belt_MapString = require("rescript/lib/js/belt_MapString.js")

var stateArray = [
  ["email", FormState.field],
  ["password", FormState.field],
]

var initialState = Belt_MapString.fromArray(stateArray)

exports.stateArray = stateArray
exports.initialState = initialState
/* initialState Not a pure module */
