// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Curry = require("rescript/lib/js/curry.js")
var Caml_option = require("rescript/lib/js/caml_option.js")
var Belt_MapString = require("rescript/lib/js/belt_MapString.js")

var field = {
  value: "",
  error: "",
}

var stateArray = [
  ["email", field],
  ["password", field],
]

var initialState = Belt_MapString.fromArray(stateArray)

function reducer(state, action) {
  if (action.TAG === /* Change */ 0) {
    return Belt_MapString.set(state, action.name, {
      value: action.value,
      error: "",
    })
  }
  var errors = action._0
  var findError = function (param) {
    return Caml_option.undefined_to_opt(errors.find(Curry.__1(param)))
  }
  return Belt_MapString.reduce(state, state, function (acc, key, value) {
    var keyError = findError(function (e) {
      return e.name === key
    })
    if (keyError !== undefined) {
      return Belt_MapString.set(acc, key, {
        value: value.value,
        error: keyError.error,
      })
    } else {
      return acc
    }
  })
}

exports.field = field
exports.stateArray = stateArray
exports.initialState = initialState
exports.reducer = reducer
/* initialState Not a pure module */
