// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var Link = require("next/link").default
var React$1 = require("@ionic/react")

function AuthenticatedLayoutMenuItem(Props) {
  var href = Props.href
  var icon = Props.icon
  var label = Props.label
  return React.createElement(Link, {
    children: React.createElement(
      React$1.IonItem,
      {
        children: null,
        button: true,
      },
      React.createElement(React$1.IonIcon, {
        slot: "start",
        icon: icon,
      }),
      React.createElement(React$1.IonLabel, {
        children: label,
      })
    ),
    href: href,
  })
}

var make = AuthenticatedLayoutMenuItem

exports.make = make
/* react Not a pure module */
