// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Test = require("rescript-test/src/Test.bs.js")
var Assert = require("../../assert/Assert.bs.js")
var FormState = require("../../../app/core/form/state/FormState.bs.js")
var Belt_MapString = require("rescript/lib/js/belt_MapString.js")

Test.test("Handles Change action", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "",
        error: "Required",
      },
    ],
    [
      "password",
      {
        value: "",
        error: "Required",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var action_1 = {
    name: "email",
    value: "myemail@gmail.com",
  }
  var action = {
    NAME: "Change",
    VAL: action_1,
  }
  var result = FormState.reducer(state, action)
  var expectedArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "",
        error: "Required",
      },
    ],
  ]
  var expected = Belt_MapString.fromArray(expectedArray)
  return Assert.assertMapEqual(result, expected)
})

Test.test("Handles SetState action", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var newStateArray = [
    [
      "email",
      {
        value: "",
        error: "required",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var newState = Belt_MapString.fromArray(newStateArray)
  var action = {
    NAME: "SetState",
    VAL: newState,
  }
  var result = FormState.reducer(state, action)
  return Assert.assertMapEqual(result, newState)
})

/*  Not a pure module */
