// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var Spread = require("../spread/Spread.bs.js")
var Caml_option = require("rescript/lib/js/caml_option.js")
var React$1 = require("@ionic/react")

function TextField(Props) {
  var name = Props.name
  var placeholder = Props.placeholder
  var label = Props.label
  var error = Props.error
  var value = Props.value
  var onIonChange = Props.onChange
  var onIonBlur = Props.onBlur
  var type_ = Props.type_
  var autofocus = Props.autofocus
  var tmp = {
    name: name,
    value: value,
    onIonChange: onIonChange,
  }
  if (placeholder !== undefined) {
    tmp.placeholder = placeholder
  }
  if (autofocus !== undefined) {
    tmp.autofocus = autofocus
  }
  if (onIonBlur !== undefined) {
    tmp.onIonBlur = Caml_option.valFromOption(onIonBlur)
  }
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement(
      React$1.IonItem,
      {
        children: null,
        lines: "full",
      },
      React.createElement(React$1.IonLabel, {
        children: label,
        position: "floating",
      }),
      React.createElement(Spread.make, {
        props: {
          type: type_,
        },
        children: React.createElement(React$1.IonInput, tmp),
      })
    ),
    React.createElement(React$1.IonNote, {
      children: error,
      color: "danger",
      className: "ion-padding",
    })
  )
}

var make = TextField

exports.make = make
/* react Not a pure module */
