// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Curry = require("rescript/lib/js/curry.js")
var Caml_option = require("rescript/lib/js/caml_option.js")

function debounce(fn, wait) {
  var timeout = {
    contents: undefined,
  }
  return function (arg) {
    var timerId = timeout.contents
    if (timerId !== undefined) {
      clearTimeout(Caml_option.valFromOption(timerId))
    }
    var timerId$1 = setTimeout(function (param) {
      return Curry._1(fn, arg)
    }, wait)
    timeout.contents = Caml_option.some(timerId$1)
  }
}

exports.debounce = debounce
/* No side effect */
