// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var SignupValidation = require("../../signup/validation/SignupValidation.bs.js")

var tooShortPassword = "Password must be at least 8 characters"

var tooLongPassword = "Password must be less than 32 characters"

var invalidEmail = "Please enter a valid email address"

var validate = SignupValidation.validate

exports.tooShortPassword = tooShortPassword
exports.tooLongPassword = tooLongPassword
exports.invalidEmail = invalidEmail
exports.validate = validate
/* SignupValidation Not a pure module */
