// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as React$1 from "@ionic/react"

function LabeledTextField(Props) {
  var name = Props.name
  var placeholder = Props.placeholder
  var label = Props.label
  var error = Props.error
  var value = Props.value
  var onChange = Props.onChange
  var tmp = {
    name: name,
    value: value,
    onChange: onChange,
  }
  if (placeholder !== undefined) {
    tmp.placeholder = placeholder
  }
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement(
      React$1.IonItem,
      {
        children: null,
        lines: "full",
      },
      React.createElement(React$1.IonLabel, {
        children: label,
        position: "floating",
      }),
      React.createElement(React$1.IonInput, tmp)
    ),
    error !== undefined
      ? React.createElement(
          "span",
          {
            className: "ion-padding",
          },
          error
        )
      : null
  )
}

var make = LabeledTextField

export { make }
/* react Not a pure module */
