// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as React$1 from "@ionic/react"

function LabeledTextField(Props) {
  var name = Props.name
  var placeholder = Props.placeholder
  var label = Props.label
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement(
      React$1.IonItem,
      {
        children: null,
        lines: "full",
      },
      React.createElement(React$1.IonLabel, {
        children: label,
        position: "floating",
      }),
      React.createElement(React$1.IonInput, {
        name: name,
        placeholder: placeholder,
      })
    ),
    React.createElement(
      "span",
      {
        className: "ion-padding",
      },
      "err"
    )
  )
}

var make = LabeledTextField

export { make }
/* react Not a pure module */
