// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as Spread from "./Spread.bs.js"
import * as React$1 from "@ionic/react"

function TextField(Props) {
  var name = Props.name
  var placeholder = Props.placeholder
  var label = Props.label
  var error = Props.error
  var value = Props.value
  var onChange = Props.onChange
  var type_ = Props.type_
  var autofocus = Props.autofocus
  var tmp = {
    name: name,
    value: value,
    onIonChange: onChange,
  }
  if (placeholder !== undefined) {
    tmp.placeholder = placeholder
  }
  if (autofocus !== undefined) {
    tmp.autofocus = autofocus
  }
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement(
      React$1.IonItem,
      {
        children: null,
        lines: "full",
      },
      React.createElement(React$1.IonLabel, {
        children: label,
        position: "floating",
      }),
      React.createElement(Spread.make, {
        props: {
          type: type_,
        },
        children: React.createElement(React$1.IonInput, tmp),
      })
    ),
    error !== undefined
      ? React.createElement(
          "span",
          {
            className: "ion-padding",
          },
          error
        )
      : null
  )
}

var make = TextField

export { make }
/* react Not a pure module */
