// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Regex = require("./regex")

var emailRegex = Regex.emailRegex

function testEmail(param) {
  return emailRegex.test(param)
}

var invalidEmail = "Please enter a valid email address"

function make(key, field) {
  if (key === "email" && !emailRegex.test(field.value)) {
    return invalidEmail
  } else {
    return ""
  }
}

exports.emailRegex = emailRegex
exports.testEmail = testEmail
exports.invalidEmail = invalidEmail
exports.make = make
/* emailRegex Not a pure module */
