// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var React$1 = require("@ionic/react")
var CreateFamily = require("../create/CreateFamily.bs.js")

function FamilyPage(Props) {
  return React.createElement(React$1.IonContent, {
    children: React.createElement(CreateFamily.make, {}),
  })
}

var make = FamilyPage

exports.make = make
/* react Not a pure module */
