// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var FormState = require("../../../../core/form/state/FormState.bs.js")
var EmailValidation = require("../../../../core/form/validations/email/EmailValidation.bs.js")
var PasswordValidation = require("../../../../core/form/validations/password/PasswordValidation.bs.js")
var RequiredValidation = require("../../../../core/form/validations/required/RequiredValidation.bs.js")

var partial_arg = [RequiredValidation.make, EmailValidation.make, PasswordValidation.make]

function validate(param) {
  return FormState.makeValidate(partial_arg, param)
}

exports.validate = validate
/* EmailValidation Not a pure module */
