// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Test = require("rescript-test/src/Test.bs.js")
var Caml_obj = require("rescript/lib/js/caml_obj.js")
var Belt_Array = require("rescript/lib/js/belt_Array.js")
var Belt_MapString = require("rescript/lib/js/belt_MapString.js")

function assertArrayEqual(result, expected) {
  return Test.assertion(
    undefined,
    undefined,
    function (res, exp) {
      return Belt_Array.eq(res, exp, Caml_obj.caml_equal)
    },
    result,
    expected
  )
}

function assertMapEqual(result, expected) {
  return Test.assertion(
    undefined,
    undefined,
    function (res, exp) {
      return Belt_MapString.eq(res, exp, Caml_obj.caml_equal)
    },
    result,
    expected
  )
}

function assertDeepEqual(result, expected) {
  return Test.assertion(undefined, undefined, Caml_obj.caml_equal, result, expected)
}

exports.assertArrayEqual = assertArrayEqual
exports.assertMapEqual = assertMapEqual
exports.assertDeepEqual = assertDeepEqual
/* Test Not a pure module */
