// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var Spread = require("../../components/spread/Spread.bs.js")
var React$1 = require("@ionic/react")

var IonContent = {}

var IonApp = {}

var Content = {
  IonContent: IonContent,
  IonApp: IonApp,
}

var IonSpinner = {}

var ProgressIndicators = {
  IonSpinner: IonSpinner,
}

var IonHeader = {}

var IonToolbar = {}

var IonTitle = {}

var Toolbar = {
  IonHeader: IonHeader,
  IonToolbar: IonToolbar,
  IonTitle: IonTitle,
}

var IonPage = {}

var Navigation = {
  IonPage: IonPage,
}

var IonItem = {}

var IonLabel = {}

var IonNote = {}

var Item = {
  IonItem: IonItem,
  IonLabel: IonLabel,
  IonNote: IonNote,
}

var IonInput = {}

var Input = {
  IonInput: IonInput,
}

var IonGrid = {}

var IonCol = {}

var IonRow = {}

var Grid = {
  IonGrid: IonGrid,
  IonCol: IonCol,
  IonRow: IonRow,
}

var IonButton = {}

function Ionic$Button$AsyncButton(Props) {
  var color = Props.color
  var expand = Props.expand
  var label = Props.label
  var isLoadingOpt = Props.isLoading
  var isLoading = isLoadingOpt !== undefined ? isLoadingOpt : false
  return React.createElement(Spread.make, {
    props: {
      type: "submit",
    },
    children: React.createElement(React$1.IonButton, {
      children: isLoading ? React.createElement(React$1.IonSpinner, {}) : label,
      color: color,
      expand: expand,
    }),
  })
}

var AsyncButton = {
  make: Ionic$Button$AsyncButton,
}

var Button = {
  IonButton: IonButton,
  AsyncButton: AsyncButton,
}

var IonToast = {}

var Toast = {
  IonToast: IonToast,
}

function Ionic$Form(Props) {
  var onSubmit = Props.onSubmit
  var children = Props.children
  return React.createElement(
    "form",
    {
      onSubmit: onSubmit,
    },
    children,
    React.createElement("input", {
      style: {
        display: "none",
      },
      type: "submit",
    })
  )
}

var Form = {
  make: Ionic$Form,
}

exports.Content = Content
exports.ProgressIndicators = ProgressIndicators
exports.Toolbar = Toolbar
exports.Navigation = Navigation
exports.Item = Item
exports.Input = Input
exports.Grid = Grid
exports.Button = Button
exports.Toast = Toast
exports.Form = Form
/* react Not a pure module */
