// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Curry = require("rescript/lib/js/curry.js")
var React = require("react")
var Spread = require("../../../core/components/spread/Spread.bs.js")
var Toggle = require("../../../core/hooks/toggle/Toggle.bs.js")
var Belt_Array = require("rescript/lib/js/belt_Array.js")
var React$1 = require("@ionic/react")
var Icons = require("ionicons/icons")

var presentProps = {
  icon: Icons.heart,
  name: "Present",
}

var lackingProps = {
  icon: Icons.heartHalf,
  name: "Lacking",
}

var missingProps = {
  icon: Icons.heartDislikeOutline,
  name: "Missing",
}

function getErrandLevelProps(level) {
  if (level === "Missing") {
    return {
      color: "danger",
      firstAction: presentProps,
      secondAction: lackingProps,
    }
  } else if (level === "Present") {
    return {
      color: "success",
      firstAction: lackingProps,
      secondAction: missingProps,
    }
  } else {
    return {
      color: "warning",
      firstAction: presentProps,
      secondAction: missingProps,
    }
  }
}

function ErrandsItem(Props) {
  var name = Props.name
  var errands = Props.errands
  var defaultToggled = Props.defaultToggled
  var handleUpdate = Props.handleUpdate
  var match = Toggle.useToggle(defaultToggled)
  var toggle = match[1]
  var toggled = match[0]
  var handleToggle = function (param) {
    return Curry._1(toggle, undefined)
  }
  var handleUpdateClick = function (e) {
    var dataset = e.currentTarget.dataset
    Curry._1(handleUpdate, dataset)
  }
  return React.createElement(React$1.IonList, {
    children: React.createElement(
      React.Fragment,
      undefined,
      React.createElement(
        React$1.IonListHeader,
        {
          children: null,
          onClick: handleToggle,
        },
        React.createElement(React$1.IonLabel, {
          children: React.createElement("h2", undefined, name),
        }),
        React.createElement(React$1.IonButton, {
          children: React.createElement(React$1.IonIcon, {
            slot: "icon-only",
            icon: toggled ? Icons.chevronDownOutline : Icons.chevronForwardOutline,
          }),
          shape: "round",
        })
      ),
      toggled
        ? Belt_Array.map(errands, function (errand) {
            var props = getErrandLevelProps(errand.level)
            var secondAction = props.secondAction
            var firstAction = props.firstAction
            var color = props.color
            return React.createElement(
              React$1.IonItemSliding,
              {
                children: null,
                key: String(errand.id),
              },
              React.createElement(React$1.IonItemOptions, {
                children: React.createElement(React$1.IonItemOption, {
                  children: React.createElement(React$1.IonIcon, {
                    icon: Icons.trashBin,
                  }),
                  color: color,
                }),
                side: "start",
              }),
              React.createElement(
                React$1.IonItem,
                {
                  children: null,
                  color: color,
                },
                React.createElement(React$1.IonLabel, {
                  children: errand.name,
                }),
                React.createElement(Spread.make, {
                  props: {
                    "data-name": firstAction.name,
                    "data-id": errand.id,
                  },
                  children: React.createElement(React$1.IonIcon, {
                    slot: "end",
                    icon: firstAction.icon,
                    onClick: handleUpdateClick,
                  }),
                }),
                React.createElement(Spread.make, {
                  props: {
                    "data-name": secondAction.name,
                    "data-id": errand.id,
                  },
                  children: React.createElement(React$1.IonIcon, {
                    slot: "end",
                    icon: secondAction.icon,
                    onClick: handleUpdateClick,
                  }),
                })
              )
            )
          })
        : null
    ),
  })
}

var make = ErrandsItem

exports.presentProps = presentProps
exports.lackingProps = lackingProps
exports.missingProps = missingProps
exports.getErrandLevelProps = getErrandLevelProps
exports.make = make
/* presentProps Not a pure module */
