// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Curry = require("rescript/lib/js/curry.js")
var React = require("react")

function useToggle(defaultOpt) {
  var $$default = defaultOpt !== undefined ? defaultOpt : false
  var match = React.useState(function () {
    return $$default
  })
  var setToggled = match[1]
  var toggle = function (param) {
    return Curry._1(setToggled, function (current) {
      return !current
    })
  }
  return [match[0], toggle]
}

exports.useToggle = useToggle
/* react Not a pure module */
