// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Curry = require("rescript/lib/js/curry.js")
var React = require("react")
var Recoil = require("recoil")
var React$1 = require("@ionic/react")

var messageState = Recoil.atom({
  key: "snackbarMessage",
  default: "",
})

function useSnackbar(param) {
  return Recoil.useSetRecoilState(messageState)
}

function Snackbar(Props) {
  var match = Recoil.useRecoilState(messageState)
  var setMessage = match[1]
  var message = match[0]
  var onDidPresent = function (param) {
    setTimeout(function (param) {
      return Curry._1(setMessage, function (param) {
        return ""
      })
    }, 10000)
  }
  return React.createElement(React$1.IonToast, {
    message: message,
    isOpen: message !== "",
    onDidPresent: onDidPresent,
  })
}

var make = Snackbar

exports.messageState = messageState
exports.useSnackbar = useSnackbar
exports.make = make
/* messageState Not a pure module */
