// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var React$1 = require("@ionic/react")
var CreateErrands = require("../create/CreateErrands.bs.js")
var ErrandsLevelsList = require("../levels-list/ErrandsLevelsList.bs.js")

function ErrandsPage(Props) {
  return React.createElement(
    React$1.IonContent,
    {
      children: null,
    },
    React.createElement(CreateErrands.make, {}),
    React.createElement(ErrandsLevelsList.make, {})
  )
}

var make = ErrandsPage

exports.make = make
/* react Not a pure module */
