// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Email = require("./email")

var email = Email.email

function testEmail(param) {
  return email.test(param)
}

exports.email = email
exports.testEmail = testEmail
/* email Not a pure module */
