// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js"
import * as React from "react"
import * as ReForm from "@rescriptbr/reform/src/ReForm.bs.js"
import * as Spread from "../../core/components/Spread.bs.js"
import * as Belt_Array from "rescript/lib/es6/belt_Array.js"
import * as React$1 from "@ionic/react"
import * as LabeledTextField from "../../core/components/LabeledTextField.bs.js"

function get(values, field) {
  if (field) {
    return values.email
  } else {
    return values.password
  }
}

function set(values, field, value) {
  if (field) {
    return {
      password: values.password,
      email: value,
    }
  } else {
    return {
      password: value,
      email: values.email,
    }
  }
}

var FormFields = {
  get: get,
  set: set,
}

var UserForm = ReForm.Make({
  set: set,
  get: get,
})

function SignupForm(Props) {
  var password = Curry._3(
    UserForm.ReSchema.Validation.nonEmpty,
    undefined,
    undefined,
    /* Password */ 0
  )
  var email = Curry._3(UserForm.ReSchema.Validation.email, undefined, undefined, /* Email */ 1)
  var form = Curry._7(
    UserForm.use,
    {
      password: "",
      email: "",
    },
    /* Schema */ {
      _0: Belt_Array.concat(email, password),
    },
    function (state) {
      console.log(state.state)
    },
    undefined,
    undefined,
    /* OnChange */ 0,
    undefined
  )
  var handleField = function (v, e) {
    return Curry._2(form.handleChange, v, e.target.value)
  }
  var handleSubmit = function ($$event) {
    $$event.preventDefault()
    console.log(1)
    return Curry._1(form.submit, undefined)
  }
  return React.createElement(
    "form",
    {
      onSubmit: handleSubmit,
    },
    React.createElement(LabeledTextField.make, {
      name: "Email",
      label: "email",
      value: form.values.email,
      onChange: function (param) {
        return handleField(/* Email */ 1, param)
      },
    }),
    React.createElement(LabeledTextField.make, {
      name: "password",
      label: "Password",
      value: form.values.password,
      onChange: function (param) {
        return handleField(/* Password */ 0, param)
      },
    }),
    React.createElement(React$1.IonRow, {
      children: React.createElement(React$1.IonCol, {
        children: React.createElement(Spread.make, {
          props: {
            type: "submit",
          },
          children: React.createElement(React$1.IonButton, {
            children: "Submit",
            color: "danger",
            expand: "block",
          }),
        }),
      }),
    })
  )
}

var Validation

var make = SignupForm

export { FormFields, UserForm, Validation, make }
/* UserForm Not a pure module */
