// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Test = require("rescript-test/src/Test.bs.js")
var Assert = require("../../assert/Assert.bs.js")
var FormState = require("../../../app/core/form/state/FormState.bs.js")
var Belt_MapString = require("rescript/lib/js/belt_MapString.js")

Test.test("Detects valid form", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "12345678",
        error: "",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var result = FormState.isValidForm(state)
  return Assert.assertDeepEqual(result, true)
})

Test.test("Detects invalid form", function (param) {
  var stateArray = [
    [
      "email",
      {
        value: "myemail@gmail.com",
        error: "",
      },
    ],
    [
      "password",
      {
        value: "",
        error: "error",
      },
    ],
  ]
  var state = Belt_MapString.fromArray(stateArray)
  var result = FormState.isValidForm(state)
  return Assert.assertDeepEqual(result, false)
})

/*  Not a pure module */
