// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var React$1 = require("@ionic/react")

function Family(Props) {
  return React.createElement(React$1.IonContent, {
    children: React.createElement(React$1.IonList, {
      children: React.createElement(React$1.IonItem, {
        children: React.createElement(React$1.IonLabel, {
          children: "hi",
        }),
      }),
    }),
  })
}

var make = Family

exports.make = make
/* react Not a pure module */
