// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")

function CreateFamily(Props) {
  return React.createElement("div", undefined)
}

var make = CreateFamily

exports.make = make
/* react Not a pure module */
