// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Page = require("../../../../core/components/page/Page.bs.js")
var React = require("react")
var SignupForm = require("../form/form/SignupForm.bs.js")

function SignupPage(Props) {
  return React.createElement(Page.make, {
    title: "Create account",
    children: React.createElement(SignupForm.make, {}),
  })
}

var make = SignupPage

exports.make = make
/* Page Not a pure module */
