// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Test = require("rescript-test/src/Test.bs.js")
var Assert = require("../../../assert/Assert.bs.js")
var CreateErrandReducer = require("../../../../app/modules/errands/create/reducer/CreateErrandReducer.bs.js")

Test.test("Handles ChangeName action", function (param) {
  var result = CreateErrandReducer.reducer(
    {
      name: "",
      level: "Present",
      toggled: true,
    },
    {
      TAG: /* ChangeName */ 0,
      _0: "hi",
    }
  )
  return Assert.assertDeepEqual(result, {
    name: "hi",
    level: "Present",
    toggled: true,
  })
})

Test.test("Handles ChangeLevel action", function (param) {
  var result = CreateErrandReducer.reducer(
    {
      name: "",
      level: "Present",
      toggled: true,
    },
    {
      TAG: /* ChangeLevel */ 1,
      _0: "Missing",
    }
  )
  return Assert.assertDeepEqual(result, {
    name: "",
    level: "Missing",
    toggled: true,
  })
})

Test.test("Handles Toggle action", function (param) {
  var result = CreateErrandReducer.reducer(
    {
      name: "",
      level: "Present",
      toggled: true,
    },
    /* Toggle */ 0
  )
  return Assert.assertDeepEqual(result, {
    name: "",
    level: "Present",
    toggled: false,
  })
})

Test.test("Handles Reset action", function (param) {
  var result = CreateErrandReducer.reducer(
    {
      name: "name",
      level: "Present",
      toggled: true,
    },
    /* Reset */ 1
  )
  return Assert.assertDeepEqual(result, {
    name: "",
    level: "Present",
    toggled: false,
  })
})

/*  Not a pure module */
