// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Clsx = require("../../rescript/clsx/Clsx.bs.js")
var Ionic = require("../../rescript/ionic/Ionic.bs.js")
var React = require("react")
var React$1 = require("@ionic/react")
var IndexModuleScss = require("./index.module.scss")

var styles = IndexModuleScss

function UnauthenticatedLayout(Props) {
  var title = Props.title
  var children = Props.children
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement(Ionic.Toolbar.MainHeader.make, {
      children: title,
    }),
    React.createElement(React$1.IonContent, {
      children: React.createElement(
        "div",
        {
          className: styles.wrapper,
        },
        React.createElement(React$1.IonGrid, {
          children: React.createElement(React$1.IonRow, {
            children: React.createElement(React$1.IonCol, {
              children: children,
              sizeMd: "5",
              sizeLg: "4",
            }),
            className: "ion-justify-content-center",
          }),
          className: Clsx.classes(["ion-padding"]),
        })
      ),
    })
  )
}

var make = UnauthenticatedLayout

exports.styles = styles
exports.make = make
/* styles Not a pure module */
