// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Curry = require("rescript/lib/js/curry.js")
var React = require("react")
var Belt_Array = require("rescript/lib/js/belt_Array.js")
var ErrandsItem = require("../item/ErrandsItem.bs.js")
var React$1 = require("@ionic/react")
var DataClient = require("next/data-client")
var Update = require("../mutations/update").default
var ErrandsLevels = require("../queries/errands-levels").default

var errandsQuery = ErrandsLevels

var updateErrand = Update

function ErrandsList(Props) {
  var match = DataClient.usePaginatedQuery(errandsQuery, undefined)
  var errandsLevelsQueryExtras = match[1]
  var errandsLevels = match[0]
  var match$1 = DataClient.useMutation(updateErrand)
  var updateErrandMutation = match$1[0]
  var handleUpdate = function (data) {
    return updateErrandMutation(data)
      .then(function (param) {
        return Curry._1(errandsLevelsQueryExtras.refetch, undefined)
      })
      .then(function (param) {
        return Promise.resolve(undefined)
      })
  }
  return React.createElement(React$1.IonContent, {
    children:
      errandsLevels !== undefined
        ? React.createElement(
            React.Fragment,
            undefined,
            Belt_Array.map(errandsLevels, function (errandLevel) {
              return React.createElement(ErrandsItem.make, {
                name: errandLevel.name,
                errands: errandLevel.errands,
                defaultToggled: errandLevel.name === "Missing",
                handleUpdate: handleUpdate,
                key: String(errandLevel.id),
              })
            })
          )
        : null,
  })
}

var make = ErrandsList

exports.errandsQuery = errandsQuery
exports.updateErrand = updateErrand
exports.make = make
/* errandsQuery Not a pure module */
