// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var SignupForm = require("../form/SignupForm.bs.js")
var React$1 = require("@ionic/react")

function SignupPage(Props) {
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement(React$1.IonHeader, {
      children: React.createElement(React$1.IonToolbar, {
        children: React.createElement(React$1.IonTitle, {
          children: "Create account",
        }),
      }),
    }),
    React.createElement(React$1.IonContent, {
      children: React.createElement(React$1.IonGrid, {
        children: React.createElement(React$1.IonRow, {
          children: React.createElement(React$1.IonCol, {
            children: React.createElement(SignupForm.make, {}),
            sizeMd: "5",
            sizeLg: "4",
          }),
          className: "ion-justify-content-center",
        }),
      }),
      className: "ion-padding",
    })
  )
}

var make = SignupPage

exports.make = make
/* react Not a pure module */
