// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js"

var field = {
  value: "",
  error: "",
}

var stateArray = [
  ["email", field],
  ["password", field],
]

var initialState = Belt_MapString.fromArray(stateArray)

function reducer(state, action) {
  if (action.TAG === /* Change */ 0) {
    return Belt_MapString.set(state, action.name, {
      value: action.value,
      error: "",
    })
  } else {
    return initialState
  }
}

export { field, stateArray, initialState, reducer }
/* initialState Not a pure module */
