// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js"
import * as Ionic from "../../../core/rescript/ionic/Ionic.bs.js"
import * as React from "react"
import * as TextField from "../../../core/components/textfield/TextField.bs.js"
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js"
import * as DataClient from "next/data-client"
import * as SignupFormReducer from "./SignupFormReducer.bs.js"
import * as SignupFormValidate from "./SignupFormValidate.bs.js"
import Signup from "app/auth/mutations/signup"

function handleSignupFormSubmit(signupMutation, data) {}

function SignupForm(Props) {
  DataClient.useMutation(Signup)
  var match = React.useReducer(SignupFormReducer.reducer, SignupFormReducer.initialState)
  var dispatch = match[1]
  var state = match[0]
  console.log(state)
  var handleSubmit = function ($$event) {
    $$event.preventDefault()
    var errors = SignupFormValidate.validate(state)
    if (errors.length > 0) {
      return Curry._1(dispatch, {
        TAG: /* SetErrors */ 1,
        _0: errors,
      })
    }
  }
  var handleChange = function (e) {
    var $$event = e.target
    var value = $$event.value
    var name = $$event.name
    return Curry._1(dispatch, {
      TAG: /* Change */ 0,
      name: name,
      value: value,
    })
  }
  return React.createElement(
    Ionic.Form.make,
    {
      onSubmit: handleSubmit,
      children: null,
    },
    React.createElement(TextField.make, {
      name: "email",
      label: "Email",
      error: Belt_MapString.getWithDefault(state, "email", SignupFormReducer.field).error,
      value: Belt_MapString.getWithDefault(state, "email", SignupFormReducer.field).value,
      onChange: handleChange,
      type_: "email",
      autofocus: true,
    }),
    React.createElement(TextField.make, {
      name: "password",
      label: "Password",
      error: Belt_MapString.getWithDefault(state, "password", SignupFormReducer.field).error,
      value: Belt_MapString.getWithDefault(state, "password", SignupFormReducer.field).value,
      onChange: handleChange,
      type_: "password",
    }),
    React.createElement(Ionic.Button.AsyncButton.make, {
      color: "danger",
      expand: "block",
      label: "Submit",
      isLoading: false,
    })
  )
}

var make = SignupForm

export { handleSignupFormSubmit, make }
/* Ionic Not a pure module */
