// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Belt_MapString = require("rescript/lib/js/belt_MapString.js")

function getOutput(state) {
  return Belt_MapString.map(state, function (value) {
    return value.value
  })
}

exports.getOutput = getOutput
/* No side effect */
