// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js"
import * as Caml_option from "rescript/lib/es6/caml_option.js"
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js"

var field = {
  value: "",
  error: "",
}

var stateArray = [
  ["email", field],
  ["password", field],
]

var initialState = Belt_MapString.fromArray(stateArray)

function reducer(state, action) {
  if (action.TAG === /* Change */ 0) {
    return Belt_MapString.set(state, action.name, {
      value: action.value,
      error: "",
    })
  }
  var errors = action._0
  var findError = function (param) {
    return Caml_option.undefined_to_opt(errors.find(Curry.__1(param)))
  }
  return Belt_MapString.reduce(state, state, function (acc, key, value) {
    var keyError = findError(function (e) {
      return e.name === key
    })
    if (keyError !== undefined) {
      return Belt_MapString.set(acc, key, {
        value: value.value,
        error: keyError.error,
      })
    } else {
      return acc
    }
  })
}

export { field, stateArray, initialState, reducer }
/* initialState Not a pure module */
