// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Belt_MapString = require("rescript/lib/js/belt_MapString.js")

function validate(state) {
  return Belt_MapString.toArray(state).reduce(function (acc, curr) {
    if (curr[1].value === "") {
      return acc.concat([
        {
          name: curr[0],
          error: "This field is required",
        },
      ])
    } else {
      return acc
    }
  }, [])
}

exports.validate = validate
/* No side effect */
