// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var initialState = {
  name: "",
  level: "Present",
  toggled: false,
}

function reducer(state, action) {
  if (typeof action === "number") {
    if (action === /* Toggle */ 0) {
      return {
        name: state.name,
        level: state.level,
        toggled: !state.toggled,
      }
    } else {
      return initialState
    }
  } else if (action.TAG === /* ChangeName */ 0) {
    return {
      name: action._0,
      level: state.level,
      toggled: state.toggled,
    }
  } else {
    return {
      name: state.name,
      level: action._0,
      toggled: state.toggled,
    }
  }
}

exports.initialState = initialState
exports.reducer = reducer
/* No side effect */
