// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var tooShortPassword = "Password must be at least 8 characters"

var tooLongPassword = "Password must be less than 32 characters"

function make(key, field) {
  if (key !== "password") {
    return ""
  }
  var length = field.value.length
  if (length < 8) {
    return tooShortPassword
  } else if (length > 32) {
    return tooLongPassword
  } else {
    return ""
  }
}

exports.tooShortPassword = tooShortPassword
exports.tooLongPassword = tooLongPassword
exports.make = make
/* No side effect */
