// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Curry = require("rescript/lib/js/curry.js")
var Snackbar = require("../../components/snackbar/Snackbar.bs.js")
var DataClient = require("next/data-client")

var Ctx = {}

function useMutation($$function, onSuccess, onError, param) {
  var setSnackbar = Snackbar.useSnackbar(undefined)
  var handleError =
    onError !== undefined
      ? onError
      : function (rawError, param, param$1) {
          return Curry._1(setSnackbar, function (param) {
            var message = rawError.message
            if (message !== undefined) {
              return message
            } else {
              return "An error happened"
            }
          })
        }
  return DataClient.useMutation($$function, {
    onSuccess: onSuccess,
    onError: handleError,
  })
}

var ReactQuery = {
  useMutation: useMutation,
}

var Link

exports.Ctx = Ctx
exports.ReactQuery = ReactQuery
exports.Link = Link
/* Snackbar Not a pure module */
