// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var Toggle = require("../../../../core/hooks/toggle/Toggle.bs.js")
var Belt_Array = require("rescript/lib/js/belt_Array.js")
var ErrandItem = require("./errand-item/ErrandItem.bs.js")
var React$1 = require("@ionic/react")
var Icons = require("ionicons/icons")

function ErrandsLevelItem(Props) {
  var name = Props.name
  var errands = Props.errands
  var defaultToggled = Props.defaultToggled
  var match = Toggle.useToggle(defaultToggled, undefined)
  var errandsToggled = match[0]
  return React.createElement(React$1.IonList, {
    children: React.createElement(
      React.Fragment,
      undefined,
      React.createElement(
        React$1.IonListHeader,
        {
          children: null,
          onClick: match[1],
        },
        React.createElement(React$1.IonLabel, {
          children: React.createElement("h2", undefined, name),
        }),
        errands.length > 0
          ? React.createElement(React$1.IonButton, {
              children: React.createElement(React$1.IonIcon, {
                slot: "icon-only",
                icon: errandsToggled ? Icons.chevronDownOutline : Icons.chevronForwardOutline,
              }),
              shape: "round",
            })
          : null
      ),
      errandsToggled
        ? Belt_Array.map(errands, function (errand) {
            return React.createElement(ErrandItem.make, {
              errand: errand,
              key: String(errand.id),
            })
          })
        : null
    ),
  })
}

var make = ErrandsLevelItem

exports.make = make
/* react Not a pure module */
