// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")
var Belt_Array = require("rescript/lib/js/belt_Array.js")
var ErrandsLevelItem = require("./level-item/ErrandsLevelItem.bs.js")
var DataClient = require("next/data-client")
var ErrandsLevels = require("../queries/errands-levels").default

var errandsLevelsQuery = ErrandsLevels

function ErrandsLevelsList(Props) {
  var match = DataClient.usePaginatedQuery(errandsLevelsQuery, undefined)
  var errandsLevels = match[0]
  if (errandsLevels !== undefined) {
    return React.createElement(
      React.Fragment,
      undefined,
      Belt_Array.map(errandsLevels, function (errandLevel) {
        return React.createElement(ErrandsLevelItem.make, {
          name: errandLevel.name,
          errands: errandLevel.errands,
          defaultToggled: errandLevel.name === "Missing",
          key: String(errandLevel.id),
        })
      })
    )
  } else {
    return null
  }
}

var make = ErrandsLevelsList

exports.errandsLevelsQuery = errandsLevelsQuery
exports.make = make
/* errandsLevelsQuery Not a pure module */
