// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var Ionic = require("../../rescript/ionic/Ionic.bs.js")
var React = require("react")
var React$1 = require("@ionic/react")
var Icons = require("ionicons/icons")
var AuthenticatedLayoutMenuItem = require("./menu-item/AuthenticatedLayoutMenuItem.bs.js")

function AuthenticatedLayout(Props) {
  var children = Props.children
  return React.createElement(
    Ionic.Menu.IonSplitPane.make,
    {
      contentId: "main-content",
      when_: "md",
      children: null,
    },
    React.createElement(
      React$1.IonMenu,
      {
        children: null,
        contentId: "main-content",
      },
      React.createElement(Ionic.Toolbar.MainHeader.make, {
        children: "Dari",
        color: "primary",
      }),
      React.createElement(React$1.IonContent, {
        children: React.createElement(
          React$1.IonList,
          {
            children: null,
          },
          React.createElement(React$1.IonListHeader, {
            children: "Navigate",
          }),
          React.createElement(
            React$1.IonMenuToggle,
            {
              children: null,
              autoHide: false,
            },
            React.createElement(AuthenticatedLayoutMenuItem.make, {
              href: "/",
              icon: Icons.home,
              label: "Home",
            }),
            React.createElement(AuthenticatedLayoutMenuItem.make, {
              href: "/errands",
              icon: Icons.bagOutline,
              label: "Errands",
            })
          )
        ),
      })
    ),
    React.createElement(
      React$1.IonPage,
      {
        children: null,
        id: "main-content",
      },
      React.createElement(React$1.IonHeader, {
        children: React.createElement(
          React$1.IonToolbar,
          {
            children: null,
          },
          React.createElement(React$1.IonButtons, {
            children: React.createElement(React$1.IonMenuToggle, {
              children: React.createElement(React$1.IonButton, {
                children: React.createElement(React$1.IonIcon, {
                  slot: "icon-only",
                  icon: Icons.menu,
                }),
              }),
              autoHide: false,
            }),
            slot: "start",
          }),
          React.createElement(React$1.IonTitle, {
            children: "Header",
          })
        ),
      }),
      React.createElement(React$1.IonContent, {
        children: children,
        className: "ion-padding",
      })
    )
  )
}

var make = AuthenticatedLayout

exports.make = make
/* Ionic Not a pure module */
