// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict"

var React = require("react")

function AuthenticatedLayout(Props) {
  var children = Props.children
  return React.createElement("div", undefined, children)
}

var make = AuthenticatedLayout

exports.make = make
/* react Not a pure module */
